#!/usr/bin/env bash
# ============================================================
#  FORGOOD — Deploy Contracts to Monad Testnet
#
#  Prerequisites:
#    1. Install Foundry: curl -L https://foundry.paradigm.xyz | bash && foundryup
#    2. Have a wallet with MON testnet tokens (faucet: https://faucet.monad.xyz)
#    3. Export your private key (WITH 0x prefix):
#         export DEPLOYER_PRIVATE_KEY=0x...your_private_key...
#
#  Usage:
#    bash scripts/deploy-contracts.sh
#
#  What it does:
#    1. Deploys MockToken (FORGOOD ERC-20)
#    2. Deploys ForGoodTreasury
#    3. Deploys MissionRegistry
#    4. Wires them together + mints 1M FORGOOD to treasury
#    5. Outputs the env vars you need for docker-compose.yml
# ============================================================

set -euo pipefail

MONAD_RPC_URL="${MONAD_RPC_URL:-https://testnet-rpc.monad.xyz}"
CONTRACTS_DIR="$(cd "$(dirname "$0")/../packages/contracts" && pwd)"

# ─── Validations ────────────────────────────────────────────

if [ -z "${DEPLOYER_PRIVATE_KEY:-}" ]; then
  echo "❌ ERROR: DEPLOYER_PRIVATE_KEY is not set."
  echo ""
  echo "   Get testnet MON from https://faucet.monad.xyz"
  echo "   Then export your private key:"
  echo "     export DEPLOYER_PRIVATE_KEY=0x...your_key..."
  echo ""
  exit 1
fi

if ! command -v forge &> /dev/null; then
  echo "❌ ERROR: Foundry (forge) is not installed."
  echo ""
  echo "   Install: curl -L https://foundry.paradigm.xyz | bash && foundryup"
  echo ""
  exit 1
fi

# Derive the agent address from the deployer key (same wallet acts as agent)
AGENT_ADDRESS=$(cast wallet address "$DEPLOYER_PRIVATE_KEY" 2>/dev/null)
if [ -z "$AGENT_ADDRESS" ]; then
  echo "❌ ERROR: Could not derive address from DEPLOYER_PRIVATE_KEY."
  exit 1
fi

echo "🚀 FORGOOD Contract Deployment"
echo "════════════════════════════════════════════"
echo "  Chain:    Monad Testnet (10143)"
echo "  RPC:      $MONAD_RPC_URL"
echo "  Agent:    $AGENT_ADDRESS"
echo "  Deployer: $AGENT_ADDRESS"
echo "════════════════════════════════════════════"
echo ""

# ─── Deploy ─────────────────────────────────────────────────

cd "$CONTRACTS_DIR"

echo "📦 Building contracts..."
forge build --quiet

echo "📤 Deploying to Monad Testnet..."
OUTPUT=$(forge script script/Deploy.s.sol:Deploy \
  --rpc-url "$MONAD_RPC_URL" \
  --broadcast \
  --private-key "$DEPLOYER_PRIVATE_KEY" \
  --legacy \
  2>&1)

echo "$OUTPUT"
echo ""

# ─── Parse addresses from output ─────────────────────────────

TOKEN_ADDR=$(echo "$OUTPUT" | grep -oP 'MockToken deployed: \K0x[0-9a-fA-F]+' || true)
TREASURY_ADDR=$(echo "$OUTPUT" | grep -oP 'ForGoodTreasury deployed: \K0x[0-9a-fA-F]+' || true)
REGISTRY_ADDR=$(echo "$OUTPUT" | grep -oP 'MissionRegistry deployed: \K0x[0-9a-fA-F]+' || true)

# Fallback: try the summary format
if [ -z "$TOKEN_ADDR" ]; then
  TOKEN_ADDR=$(echo "$OUTPUT" | grep -oP 'Token:\s+\K0x[0-9a-fA-F]+' || true)
fi
if [ -z "$TREASURY_ADDR" ]; then
  TREASURY_ADDR=$(echo "$OUTPUT" | grep -oP 'Treasury:\s+\K0x[0-9a-fA-F]+' || true)
fi
if [ -z "$REGISTRY_ADDR" ]; then
  REGISTRY_ADDR=$(echo "$OUTPUT" | grep -oP 'Registry:\s+\K0x[0-9a-fA-F]+' || true)
fi

if [ -z "$TOKEN_ADDR" ] || [ -z "$TREASURY_ADDR" ]; then
  echo "❌ Could not parse deployed addresses from output."
  echo "   Check the forge output above for errors."
  exit 1
fi

# ─── Output ─────────────────────────────────────────────────

echo ""
echo "════════════════════════════════════════════"
echo "  ✅ DEPLOYMENT SUCCESSFUL"
echo "════════════════════════════════════════════"
echo ""
echo "Add these to your .env file or export them before running docker-compose:"
echo ""
echo "  export AGENT_PRIVATE_KEY=$DEPLOYER_PRIVATE_KEY"
echo "  export TREASURY_ADDRESS=$TREASURY_ADDR"
echo "  export FORGOOD_TOKEN_ADDRESS=$TOKEN_ADDR"
echo "  export REGISTRY_ADDRESS=$REGISTRY_ADDR"
echo ""
echo "Or create a .env file:"
echo ""

# Write to .env.contracts
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.contracts"
cat > "$ENV_FILE" <<EOF
# FORGOOD Contract Addresses — deployed to Monad Testnet (chain 10143)
# Generated by scripts/deploy-contracts.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
AGENT_PRIVATE_KEY=$DEPLOYER_PRIVATE_KEY
TREASURY_ADDRESS=$TREASURY_ADDR
FORGOOD_TOKEN_ADDRESS=$TOKEN_ADDR
REGISTRY_ADDRESS=${REGISTRY_ADDR:-}
EOF

echo "  📄 Written to: $ENV_FILE"
echo ""
echo "To use with docker-compose:"
echo "  source .env.contracts && docker compose up -d --build"
echo ""
